name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      opendata-db:
        image: postgres:alpine
        env:
          POSTGRES_DB: opendata
          POSTGRES_PASSWORD: opendata
          POSTGRES_PORT: 5432
          POSTGRES_USER: opendata
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clone this repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install python lint dependencies
        run: python -m pip install ruff mypy

      - name: Run ruff check
        run: ruff check --config ruff.toml

      - name: Run ruff check format
        run: ruff format --check
